/* Autogenerated file for xtype configuration
 * by running bin2ascii with xtype.ini file.
 * The xtype header should be updated by developer
 * once the xtype.ini configuration is updated.
 * --------------! DO NOT EDIT -----------------*/
#ifndef XTYPE_HPP_
#define XTYPE_HPP_

#include <tools/bin-tool.hpp>

use_ns(e2prom)

extern const char* user_18000[12];
extern const char* user_18001[14];
extern const char* user_18002[6];
extern const char* user_18005[10];
extern const char* user_18006[10];
extern const char* user_18007[14];
extern const char* user_18008[8];
extern const char* user_18009[10];
extern const char* user_18010[6];
extern const char* user_18011[12];
extern const char* user_18012[14];
extern const char* user_18013[14];
extern const char* user_18014[10];
extern const char* user_18016[14];
extern const char* user_18018[10];
extern const char* user_18030[8];
extern const char* user_18031[10];
extern const char* user_18048[10];
extern const char* user_18049[16];
extern const char* user_18060[14];
extern const char* user_18061[14];
extern const char* user_18070[10];
extern const char* user_18080[12];
extern const char* user_18500[16];
extern const char* user_18501[16];
extern const char* user_18502[6];
extern void init_xtype(UserBlkTps &ubt);
#endif /* XTYPE_HPP_ */

